# Generated by Django 4.2.13 on 2024-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontype',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
