# Generated by Django 4.2.13 on 2025-04-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_reactiontype_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментари'},
        ),
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name': 'Харесване на коментар', 'verbose_name_plural': 'Харесвания на коментари'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Изображение на публикация', 'verbose_name_plural': 'Изображения на публикации'},
        ),
        migrations.AlterModelOptions(
            name='reactiontype',
            options={'verbose_name': 'Тип реакция', 'verbose_name_plural': 'Типове реакции'},
        ),
        migrations.AlterModelOptions(
            name='savedposts',
            options={'verbose_name': 'Записана публикация', 'verbose_name_plural': 'Записани публикации'},
        ),
    ]
