# Generated by Django 4.2.13 on 2025-04-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_space_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Теми'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Етикет', 'verbose_name_plural': 'Етикети'},
        ),
        migrations.AlterModelOptions(
            name='userspacefollow',
            options={'verbose_name': 'Последване на тема', 'verbose_name_plural': 'Последвания на теми'},
        ),
    ]
