# Generated by Django 4.2.13 on 2025-04-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профил', 'verbose_name_plural': 'Профила'},
        ),
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'Последване', 'verbose_name_plural': 'Последвания'},
        ),
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-reported_on'], 'verbose_name': 'Доклад за потребител', 'verbose_name_plural': 'Доклади за потребители'},
        ),
    ]
