# Generated by Django 4.2.13 on 2025-04-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Нотификация', 'verbose_name_plural': 'Нотификации'},
        ),
    ]
